# Generated by Django 4.2.20 on 2025-04-22 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
    # Заменить или удалить ссылку на wanderlist_app
    ('restaurant_app', '0001_initial'),  # исправленная зависимость
]


    operations = [
        migrations.AddField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
    ]
